module.exports = {
	animation: require("./animation"),
	core: require("./core"),
	display: require("./display"),
	errors: require("./errors"),
	events: require("./events"),
	extensions: require("./extensions"),
	filters: require("./filters"),
	geom: require("./geom"),
	rendering: require("./rendering"),
	styles: require("./styles"),
	text: require("./text"),
	textures: require("./textures"),
	utils: require("./utils"),
}