import starling.animation.DelayedCall;
import starling.animation.IAnimatable;
import starling.animation.Juggler;
import starling.animation.Transitions;
import starling.animation.Tween;
import starling.core.RenderSupport;
import starling.core.Starling;
//import starling.core.starling_internal;
import starling.core.StatsDisplay;
import starling.display.BlendMode;
import starling.display.Button;
import starling.display.ButtonState;
import starling.display.Canvas;
import starling.display.DisplayObject;
import starling.display.DisplayObjectContainer;
import starling.display.Image;
import starling.display.MovieClip;
import starling.display.Quad;
import starling.display.QuadBatch;
import starling.display.Sprite;
import starling.display.Sprite3D;
import starling.display.Stage;
import starling.errors.AbstractClassError;
import starling.errors.AbstractMethodError;
import starling.errors.MissingContextError;
import starling.events.EnterFrameEvent;
import starling.events.Event;
import starling.events.EventDispatcher;
import starling.events.KeyboardEvent;
import starling.events.ResizeEvent;
import starling.events.Touch;
import starling.events.TouchEvent;
import starling.events.TouchMarker;
import starling.events.TouchPhase;
import starling.events.TouchProcessor;
import starling.filters.BlurFilter;
import starling.filters.ColorMatrixFilter;
import starling.filters.DisplacementMapFilter;
import starling.filters.FragmentFilter;
import starling.filters.FragmentFilterMode;
import starling.text.BitmapChar;
import starling.text.BitmapFont;
import starling.text.TextField;
import starling.text.TextFieldAutoSize;
import starling.textures.AtfData;
import starling.textures.ConcreteTexture;
import starling.textures.RenderTexture;
import starling.textures.SubTexture;
import starling.textures.Texture;
import starling.textures.TextureAtlas;
import starling.textures.TextureOptions;
import starling.textures.TextureSmoothing;
import starling.utils.ArrayUtil;
import starling.utils.AssetManager;
//import starling.utils.cleanMasterString;
import starling.utils.Color;
//import starling.utils.deg2rad;
//import starling.utils.execute;
//import starling.utils.formatString;
//import starling.utils.getNextPowerOfTwo;
import starling.utils.HAlign;
import starling.utils.IntRect;
import starling.utils.MathUtil;
import starling.utils.MatrixUtil;
import starling.utils.Max;
import starling.utils.MaxRectsBinPack;
import starling.utils.PowerOfTwo;
//import starling.utils.rad2deg;
import starling.utils.RectangleUtil;
import starling.utils.SafeCast;
import starling.utils.ScaleMode;
import starling.utils.StringUtil;
import starling.utils.SystemUtil;
//import starling.utils.transformCoords;
import starling.utils.VAlign;
import starling.utils.VertexData;

#if codegen
class ImportAll
{
    public static function main()
    {
        untyped
        {
            exports.starling_animation_DelayedCall = starling_animation_DelayedCall;
            exports.starling_animation_IAnimatable = starling_animation_IAnimatable;
            exports.starling_animation_Juggler = starling_animation_Juggler;
            exports.starling_animation_Transitions = starling_animation_Transitions;
            exports.starling_animation_Tween = starling_animation_Tween;
            exports.starling_core_RenderSupport = starling_core_RenderSupport;
            exports.starling_core_Starling = starling_core_Starling;
//          exports.starling_core_starling_internal = starling_core_starling_internal;
            exports.starling_core_StatsDisplay = starling_core_StatsDisplay;
            exports.starling_display_BlendMode = starling_display_BlendMode;
            exports.starling_display_Button = starling_display_Button;
            exports.starling_display_ButtonState = starling_display_ButtonState;
			exports.starling_display_Canvas = starling_display_Canvas;
            exports.starling_display_DisplayObject = starling_display_DisplayObject;
            exports.starling_display_DisplayObjectContainer = starling_display_DisplayObjectContainer;
            exports.starling_display_Image = starling_display_Image;
            exports.starling_display_MovieClip = starling_display_MovieClip;
            exports.starling_display_Quad = starling_display_Quad;
            exports.starling_display_QuadBatch = starling_display_QuadBatch;
            exports.starling_display_Sprite = starling_display_Sprite;
            exports.starling_display_Sprite3D = starling_display_Sprite3D;
            exports.starling_display_Stage = starling_display_Stage;
            exports.starling_errors_AbstractClassError = starling_errors_AbstractClassError;
            exports.starling_errors_AbstractMethodError = starling_errors_AbstractMethodError;
            exports.starling_errors_MissingContextError = starling_errors_MissingContextError;
            exports.starling_events_EnterFrameEvent = starling_events_EnterFrameEvent;
            exports.starling_events_Event = starling_events_Event;
            exports.starling_events_EventDispatcher = starling_events_EventDispatcher;
            exports.starling_events_KeyboardEvent = starling_events_KeyboardEvent;
            exports.starling_events_ResizeEvent = starling_events_ResizeEvent;
            exports.starling_events_Touch = starling_events_Touch;
            exports.starling_events_TouchEvent = starling_events_TouchEvent;
            exports.starling_events_TouchMarker = starling_events_TouchMarker;
            exports.starling_events_TouchPhase = starling_events_TouchPhase;
            exports.starling_events_TouchProcessor = starling_events_TouchProcessor;
            exports.starling_filters_BlurFilter = starling_filters_BlurFilter;
            exports.starling_filters_ColorMatrixFilter = starling_filters_ColorMatrixFilter;
            exports.starling_filters_DisplacementMapFilter = starling_filters_DisplacementMapFilter;
            exports.starling_filters_FragmentFilter = starling_filters_FragmentFilter;
            exports.starling_filters_FragmentFilterMode = starling_filters_FragmentFilterMode;
            exports.starling_text_BitmapChar = starling_text_BitmapChar;
            exports.starling_text_BitmapFont = starling_text_BitmapFont;
            exports.starling_text_TextField = starling_text_TextField;
            exports.starling_text_TextFieldAutoSize = starling_text_TextFieldAutoSize;
            exports.starling_textures_AtfData = starling_textures_AtfData;
            exports.starling_textures_ConcreteTexture = starling_textures_ConcreteTexture;
            exports.starling_textures_RenderTexture = starling_textures_RenderTexture;
            exports.starling_textures_SubTexture = starling_textures_SubTexture;
            exports.starling_textures_Texture = starling_textures_Texture;
            exports.starling_textures_TextureAtlas = starling_textures_TextureAtlas;
            exports.starling_textures_TextureOptions = starling_textures_TextureOptions;
            exports.starling_textures_TextureSmoothing = starling_textures_TextureSmoothing;
            exports.starling_utils_ArrayUtil = starling_utils_ArrayUtil;
            exports.starling_utils_AssetManager = starling_utils_AssetManager;
//          exports.starling_utils_cleanMasterString = starling_utils_cleanMasterString;
            exports.starling_utils_Color = starling_utils_Color;
//          exports.starling_utils_deg2rad = starling_utils_deg2rad;
//          exports.starling_utils_execute = starling_utils_execute;
//          exports.starling_utils_formatString = starling_utils_formatString;
//          exports.starling_utils_getNextPowerOfTwo = starling_utils_getNextPowerOfTwo;
            exports.starling_utils_HAlign = starling_utils_HAlign;
            exports.starling_utils_IntRect = starling_utils_IntRect;
            exports.starling_utils_MathUtil = starling_utils_MathUtil;
            exports.starling_utils_MatrixUtil = starling_utils_MatrixUtil;
            exports.starling_utils_Max = starling_utils_Max;
            exports.starling_utils_MaxRectsBinPack = starling_utils_MaxRectsBinPack;
            exports.starling_utils_PowerOfTwo = starling_utils_PowerOfTwo;
//          exports.starling_utils_rad2deg = starling_utils_rad2deg;
            exports.starling_utils_RectangleUtil = starling_utils_RectangleUtil;
            exports.starling_utils_SafeCast = starling_utils_SafeCast;
            exports.starling_utils_ScaleMode = starling_utils_ScaleMode;
            exports.starling_utils_StringUtil = starling_utils_StringUtil;
            exports.starling_utils_SystemUtil = starling_utils_SystemUtil;
//          exports.starling_utils_transformCoords = starling_utils_transformCoords;
            exports.starling_utils_VAlign = starling_utils_VAlign;
            exports.starling_utils_VertexData = starling_utils_VertexData;
        }
    }

    public static function __init__()
    {
        untyped
        {
            var lime_graphics_ImageChannel = require("lime").lime_graphics_ImageChannel;
            var lime_graphics_ImageType = require("lime").lime_graphics_ImageType;
            var lime_graphics_RenderContext = require("lime").lime_graphics_RenderContext;
            var lime_ui_MouseCursor = require("lime").lime_ui_MouseCursor;
            var lime_utils_CompressionAlgorithm = require("lime").lime_utils_CompressionAlgorithm;
            var openfl_display_BlendMode = require("openfl").openfl_display_BlendMode;
            var openfl_display_CapsStyle = require("openfl").openfl_display_CapsStyle;
            var openfl_display_GradientType = require("openfl").openfl_display_GradientType;
            var openfl_display_GraphicsPathWinding = require("openfl").openfl_display_GraphicsPathWinding;
            var openfl_display_GraphicsDataType = require("openfl").openfl_display_GraphicsDataType;
            var openfl_display_InterpolationMethod = require("openfl").openfl_display_InterpolationMethod;
            var openfl_display_JointStyle = require("openfl").openfl_display_JointStyle;
            var openfl_display_LineScaleMode = require("openfl").openfl_display_LineScaleMode;
            var openfl_display_PixelSnapping = require("openfl").openfl_display_PixelSnapping;
            var openfl_display_SpreadMethod = require("openfl").openfl_display_SpreadMethod;
            var openfl_display_StageAlign = require("openfl").openfl_display_StageAlign;
            var openfl_display_StageDisplayState = require("openfl").openfl_display_StageDisplayState;
            var openfl_display_StageQuality = require("openfl").openfl_display_StageQuality;
            var openfl_display_StageScaleMode = require("openfl").openfl_display_StageScaleMode;
            var openfl_display_TriangleCulling = require("openfl").openfl_display_TriangleCulling;
            var openfl_display3D_Context3DBufferUsage = require("openfl").openfl_display3D_Context3DBufferUsage;
            var openfl_display3D_Context3DMipFilter = require("openfl").openfl_display3D_Context3DMipFilter;
            var openfl_display3D_Context3DProfile = require("openfl").openfl_display3D_Context3DProfile;
            var openfl_display3D_Context3DProgramType = require("openfl").openfl_display3D_Context3DProgramType;
            var openfl_display3D_Context3DRenderMode = require("openfl").openfl_display3D_Context3DRenderMode;
            var openfl_display3D_Context3DTextureFilter = require("openfl").openfl_display3D_Context3DTextureFilter;
            var openfl_display3D_Context3DTextureFormat = require("openfl").openfl_display3D_Context3DTextureFormat;
            var openfl_display3D_Context3DVertexBufferFormat = require("openfl").openfl_display3D_Context3DVertexBufferFormat;
            var openfl_display3D_Context3DWrapMode = require("openfl").openfl_display3D_Context3DWrapMode;
            var openfl_events_EventPhase = require("openfl").openfl_events_EventPhase;
            var openfl_geom_Orientation3D = require("openfl").openfl_geom_Orientation3D;
            var openfl_net_URLLoaderDataFormat = require("openfl").openfl_net_URLLoaderDataFormat;
            var openfl_system_TouchscreenType = require("openfl").openfl_system_TouchscreenType;
            var openfl_text_AntiAliasType = require("openfl").openfl_text_AntiAliasType;
            var openfl_text_FontStyle = require("openfl").openfl_text_FontStyle;
            var openfl_text_FontType = require("openfl").openfl_text_FontType;
            var openfl_text_GridFitType = require("openfl").openfl_text_GridFitType;
            var openfl_text_TextFieldAutoSize = require("openfl").openfl_text_TextFieldAutoSize;
            var openfl_text_TextFieldType = require("openfl").openfl_text_TextFieldType;
            var openfl_text_TextFormatAlign = require("openfl").openfl_text_TextFormatAlign;
            var openfl_ui_MultitouchInputMode = require("openfl").openfl_ui_MultitouchInputMode;
        }
    }
}
#end